version: '2'
networks:
    micronet:

services:
    ## Consul
    consul-bootstrap:
      image          : consul
      container_name : consul-bootstrap
      command        :
        - "agent"
        - "-server"
        - "-bootstrap"
        - "-ui"
        - "-data-dir=/tmp"
        - "-advertise=${DOCKER_MACHINE_IP}"
        - "-client=0.0.0.0"
        - "-node=bootstrap-node"
        - "-node-id=102b597f-0b4c-4702-985e-327a5a022cc7"
      volumes        : [ "./tmp/consul-bootstrap:/tmp/consul" ]
      networks       : [ micronet ]
      ports          :
        - "8400:8400"
        - "8500:8500"
        - "8600:8600/udp"
  
    # Registrator
    registrator:
      image         : gliderlabs/registrator
      container_name: registrator
      command       : ["-ip", "${DOCKER_MACHINE_IP}", "consul://consul-bootstrap:8500"]
      volumes       : [ "/var/run/docker.sock:/tmp/docker.sock" ]
      networks      : [ micronet ]
      depends_on    : [ consul-bootstrap ]
  
    # Flask services
    hello-server:
      build         : .
      container_name: hello-server
      working_dir   : /usr/local/app/consul-docker-test
      entrypoint    : ""
      command       : [ "python", "-m", "flask-server.hello-server" ]
      networks      : [ micronet ]
      depends_on    : [ registrator ]
      ports         : [ "80" ]
      environment   :
        - SERVICE_NAME=hello-server

    call-server:
      build         : .
      container_name: call-server
      working_dir   : /usr/local/app/consul-docker-test
      entrypoint    : ""
      command       : [ "python", "-m", "flask-server.call-server" ]
      networks      : [ micronet ]
      depends_on    : [ registrator ]
      ports         : [ "80" ]
      environment   :
        - SERVICE_NAME=call-server